CREATE DATABASE Pubs
USE Pubs;


--TABLA PUB--
CREATE TABLE PUB(
codigo INT IDENTITY(1,1), --PRIMARY
nombre NVARCHAR(100) NOT NULL,
domicilio NVARCHAR(250),
fechaApertura DATE NOT NULL,
horario NVARCHAR(15) NOT NULL,
codigoLocalidad INT NOT NULL, --FOREIGN

CONSTRAINT pk_PUB_codigo PRIMARY KEY(codigo),
CONSTRAINT ch_PUB_horario CHECK(horario IN ('HORARIO1' , 'HORARIO2' , 'HORARIO3')),
CONSTRAINT fk_PUB_codigoLocalidad FOREIGN KEY (codigoLocalidad) REFERENCES LOCALIDAD(codigoLocalidad)
);


--TABLA TITULAR--
CREATE TABLE TITULAR(
DNITitular INT NOT NULL, --PRIMARY
nombre NVARCHAR(100) NOT NULL,
domicilio NVARCHAR(250),
codigoPUB INT NOT NULL, --FOREIGN

CONSTRAINT pk_TITULAR_DNITitular PRIMARY KEY(DNITitular),
CONSTRAINT fk_TITULAR_codigoPUB FOREIGN KEY(codigoPUB) REFERENCES PUB(codigo)
);


--TABLA EMPLEADO--
CREATE TABLE EMPLEADO(
DNIEmpleado INT NOT NULL, --PRIMARY
nombre NVARCHAR(100) NOT NULL,
domicilio NVARCHAR(250)

CONSTRAINT pk_EMPLEADO_DNIEmpleado PRIMARY KEY (DNIEmpleado)
);


--TABLA ARTICULO--
CREATE TABLE ARTICULO(
codigoArticulo INT NOT NULL, --PRIMARY
nombre NVARCHAR(100) NOT NULL,
cantidad INT NOT NULL,
precio INT NOT NULL, -->0
codigoPUB INT NOT NULL, --FOREIGN

CONSTRAINT pk_ARTICULO_codigoArticulo PRIMARY KEY(codigoArticulo),
CONSTRAINT ch_ARTICULO_precio CHECK (precio > 0),
CONSTRAINT fk_ARTICULO_codigoPUB FOREIGN KEY (codigoPUB) REFERENCES PUB(codigo)
);


--TABLA LOCALIDAD--
CREATE TABLE LOCALIDAD(
codigoLocalidad INT NOT NULL, --PRIMARY
nombre NVARCHAR(100) NOT NULL,

CONSTRAINT pk_LOCALIDAD_codigoLocalidad PRIMARY KEY (codigoLocalidad)
);


--TABLA PUBEMPLEADO--
CREATE TABLE PUB_EMPLEADO(
codigoPUB INT NOT NULL,
DNIEmpleado INT NOT NULL,
funcion NVARCHAR(100) NOT NULL,

CONSTRAINT pk_PUB_EMPLEADO PRIMARY KEY (codigoPUB, DNIEmpleado, funcion),
CONSTRAINT ch_PUB_EMPLEADO_funcion CHECK (funcion IN ('CAMARERO' , 'SEGURIDAD' , 'LIMPIEZA'))
);